title: Deep Reinforcement Learning for Computer Games
subtitle: UEF Summer School, August 2019
url: "https://abrahamwoubie.github.io"
subtitle_url: "http://www.uef.fi/en/web/summerschool/deep_reinforcement_learning"
baseurl: "/summerschool"

markdown: kramdown

google_analytics: UA-119760540-1

sass:
    style: compressed
    sass_dir: _sass
